<!DOCTYPE html>
<html>
<head>
</head>
<body>
	<style type="text/css">
		table tr td,
		table tr th .size{
			font-size: 11pt;
		}

        table tr td,
        table tr th .bottom{
	        font-size: 9pt;
            border-bottom: 1px solid black;
            align: left;
            valign: bottom;
            font-color: black;
        }
        
	</style>
	<table border="1" cellspacing="0" cellpadding="0" style="width:100%">
        <tbody>
            <tr>
                <td width="3.5 cm" rowspan="3" valign="top">
                    <p align="center">
                        <img
                            width="75"
                            height="56"
                            src=""
                        />
                    </p>
                </td>
                <td width="10 cm"rowspan="3">
                    <p align="center">
                        <strong>PT. BRINGIN GIGANTARA</strong>
                    </p>
                </td>
               <td>
                    <p>&nbsp; BG-KLY-FRM-004-01</p>
                </td>
            </tr>
            <tr>
               <td>
                    <p>&nbsp; REVISI 00</p>
                </td>
            </tr>
            <tr>
               <td>
                    <p>&nbsp; 30 JUNI 2017</p>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <p align="center"> 
                        <strong>REGISTER BUKU BESAR CPC</strong>
                    </p>
                </td>
            </tr>
        </tbody>
    </table>
    <br/>
    <table border="1" cellspacing="0" cellpadding="0" style="width:100%">
        <tbody>
            <tr align="center">
                <td rowspan="3">
                    <p><strong>NO</strong></p>
                </td>
                <td rowspan="3">
                    <p><strong>TANGGAL</strong></p>
                </td>
                <td rowspan="3">
                    <p><strong>KETERANGAN</strong></p>
                </td>
                <td colspan="6">
                    <p><strong>SALDO AWAL</strong></p>
                </td>
                <td colspan="6">
                    <p><strong>TAMBAHAN KAS</strong></p>
                </td>
                <td colspan="6">
                    <p><strong>REPLENISH ATM</strong></p>
                </td>
                <td colspan="6">
                    <p><strong>&nbsp;RETURN ATM</strong></p>
                </td>
                <td colspan="6">
                    <p><strong>SALDO AKHIR</strong></p>
                </td>
                <td rowspan="3">
                    <p><strong>Total (RP)</strong></p>
                </td>
            </tr>
            <tr align="center">
                <td colspan="2">
                    <p><strong>DENOM 100.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 50.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 20.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 100.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 50.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 20.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 100.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 50.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 20.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 100.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 50.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 20.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 100.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 50.000</strong></p>
                </td>
                <td colspan="2">
                    <p><strong>DENOM 20.000</strong></p>
                </td>
            </tr>
            <tr align="center">    
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>    
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
               <td>
                    <p><strong>LEMBAR</strong></p>
                </td>
               <td>
                    <p><strong>NILAI(RP)</strong></p>
                </td>
            </tr>
            <tr align="center">
                <td>
                    <p>1</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr align="center">
                <td>
                    <p>2</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr align="center">
                <td>
                    <p>3</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr align="center">
                <td>
                    <p>4</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr align="center">
                <td>
                    <p>5</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr align="center">
                <td>
                    <p>6</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr align="center">
                <td>
                    <p>Dst.</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr align="center">
                <td colspan="3">
                    <p>Jumlah</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
               <td>
                    <p>&nbsp;</p>
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>